name: Test

on:
  push:
    branches: [4.0.0]
  pull_request:
    branches: [4.0.0]
  workflow_call:

jobs:
  privoxy:
    strategy:
      matrix:
        privoxy_version: [4.0.0]
        python-version: [3.13]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            .venv
            .cache
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to current branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: latest

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run pytest
        run: poetry run pytest --privoxy-version ${{ matrix.privoxy_version }} --no-cache -v
